# Generated by Django 4.1.1 on 2022-09-18 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=70)),
                ('localidad', models.CharField(max_length=70)),
                ('municipio', models.CharField(max_length=70)),
                ('nombre', models.TextField(max_length=100)),
                ('edad_activo', models.SmallIntegerField(default=0)),
                ('tipo_persona', models.CharField(max_length=50)),
                ('tipo_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=70)),
                ('localidad', models.CharField(max_length=70)),
                ('municipio', models.CharField(max_length=70)),
                ('nombre', models.TextField(max_length=100)),
                ('edad_activo', models.SmallIntegerField(default=0)),
                ('tipo_persona', models.CharField(max_length=50)),
                ('tipo_cargo', models.CharField(max_length=50)),
                ('ratio', models.FloatField(default=0.0)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='demonstration.historial')),
            ],
        ),
        migrations.RunSQL(sql="ALTER TABLE demonstration_persona ADD FULLTEXT(nombre)")
    ]
